Models/Entry.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace miniProiect2.Models
{
    public class Entry
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public int? PartnerId { get; set; }
        [ForeignKey("PartnerId")]
        public virtual Partner? Partner { get; set; }
        public int? GestionId { get; set; }
        [ForeignKey("GestionId")]
        public virtual Gestion? Gestion { get; set; }
    }
}

Pages/DetailedEntries/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.DetailedEntries
{
    public class CreateModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public CreateModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["Id"] = new SelectList(_context.Entries, "Id", "Id");
        ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id");
            return Page();
        }

        [BindProperty]
        public DetailedEntry DetailedEntry { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            _context.DetailedEntries.Add(DetailedEntry);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/DetailedEntries/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.DetailedEntries
{
    public class DeleteModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public DeleteModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        [BindProperty]
        public DetailedEntry DetailedEntry { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedentry = await _context.DetailedEntries.FirstOrDefaultAsync(m => m.Id == id);

            if (detailedentry is not null)
            {
                DetailedEntry = detailedentry;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedentry = await _context.DetailedEntries.FindAsync(id);
            if (detailedentry != null)
            {
                DetailedEntry = detailedentry;
                _context.DetailedEntries.Remove(DetailedEntry);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/DetailedEntries/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.DetailedEntries
{
    public class DetailsModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public DetailsModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        public DetailedEntry DetailedEntry { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedentry = await _context.DetailedEntries.FirstOrDefaultAsync(m => m.Id == id);


            if (detailedentry is not null)
            {
                DetailedEntry = detailedentry;

                return Page();
            }

            return NotFound();
        }
    }
}

Pages/DetailedEntries/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.DetailedEntries
{
    public class EditModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public EditModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        [BindProperty]
        public DetailedEntry DetailedEntry { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedentry =  await _context.DetailedEntries.FirstOrDefaultAsync(m => m.Id == id);
            if (detailedentry == null)
            {
                return NotFound();
            }
            DetailedEntry = detailedentry;
           ViewData["Id"] = new SelectList(_context.Entries, "Id", "Id");
           ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(DetailedEntry).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DetailedEntryExists(DetailedEntry.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool DetailedEntryExists(int id)
        {
            return _context.DetailedEntries.Any(e => e.Id == id);
        }
    }
}

Pages/DetailedExits/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.DetailedExits
{
    public class CreateModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public CreateModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["ExitId"] = new SelectList(_context.Exits, "Id", "Id");
        ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id");
            return Page();
        }

        [BindProperty]
        public DetailedExit DetailedExit { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.DetailedExits.Add(DetailedExit);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/DetailedExits/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.DetailedExits
{
    public class DeleteModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public DeleteModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        [BindProperty]
        public DetailedExit DetailedExit { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedexit = await _context.DetailedExits.FirstOrDefaultAsync(m => m.Id == id);

            if (detailedexit is not null)
            {
                DetailedExit = detailedexit;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedexit = await _context.DetailedExits.FindAsync(id);
            if (detailedexit != null)
            {
                DetailedExit = detailedexit;
                _context.DetailedExits.Remove(DetailedExit);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/DetailedExits/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.DetailedExits
{
    public class DetailsModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public DetailsModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        public DetailedExit DetailedExit { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedexit = await _context.DetailedExits.FirstOrDefaultAsync(m => m.Id == id);

            if (detailedexit is not null)
            {
                DetailedExit = detailedexit;

                return Page();
            }

            return NotFound();
        }
    }
}

Pages/DetailedExits/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.DetailedExits
{
    public class EditModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public EditModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        [BindProperty]
        public DetailedExit DetailedExit { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailedexit =  await _context.DetailedExits.FirstOrDefaultAsync(m => m.Id == id);
            if (detailedexit == null)
            {
                return NotFound();
            }
            DetailedExit = detailedexit;
           ViewData["ExitId"] = new SelectList(_context.Exits, "Id", "Id");
           ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(DetailedExit).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DetailedExitExists(DetailedExit.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool DetailedExitExists(int id)
        {
            return _context.DetailedExits.Any(e => e.Id == id);
        }
    }
}

Pages/Entries/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.Entries
{
    public class DeleteModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public DeleteModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        [BindProperty]
        public Entry Entry { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.Entries.FirstOrDefaultAsync(m => m.Id == id);

            if (entry is not null)
            {
                Entry = entry;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.Entries.FindAsync(id);
            var detailedExit = from de in _context.DetailedEntries
                               where de.EntryId == Entry.Id
                               select de;
            if (entry != null)
            {
                Entry = entry;

                if (detailedExit.Any())
                {
                    foreach (var de in detailedExit)
                    {
                        _context.DetailedEntries.Remove(de);
                    }
                }

                _context.Entries.Remove(Entry);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Entries/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using miniProiect2.Data;
using miniProiect2.Models;

namespace miniProiect2.Pages.Entries
{
    public class IndexModel : PageModel
    {
        private readonly miniProiect2.Data.miniProiect2Context _context;

        public IndexModel(miniProiect2.Data.miniProiect2Context context)
        {
            _context = context;
        }

        public IList<Entry> Entry { get; set; } = default!;
        [BindProperty]
        public Entry SelectedEntry { get; set; } = default!;
        [BindProperty]
        public DetailedEntry detailedEntry { get; set; } = default!;

        public async Task OnGetAsync()
        {
            // Retrieve the detailedEntry from TempData if available
            if (TempData["DetailedEntry"] != null)
            {
                detailedEntry = JsonConvert.DeserializeObject<DetailedEntry>((string)TempData["DetailedEntry"]);
            }

            // Fetch entries for the page
            Entry = await _context.Entries
                .Include(e => e.Gestion)
                .Include(e => e.Partner)
                .ToListAsync();
        }

        public async Task<IActionResult> OnPostSelectAsync(int Id)
        {
            // Fetch the selected entry
            SelectedEntry = 
                await _context.Entries
                .Include(e => e.Gestion)
                .Include(e => e.Partner)
                .FirstOrDefaultAsync(m => m.Id == Id);

            // Fetch the detailed entry associated with the selected entry
            detailedEntry = await _context.DetailedEntries
                .Include(d => d.Product)
                .FirstOrDefaultAsync(m => m.EntryId == Id);

            // Store detailedEntry in TempData for persistence
            if (detailedEntry != null)
            {
                TempData["DetailedEntry"] = JsonConvert.SerializeObject(detailedEntry);
            }

            return RedirectToPage();
        }
    }
}

Pages/Entries/Create.cshtml
@page
@model miniProiect2.Pages.Entries.CreateModel

        @{
        ViewData["Title"] = "Create";
        }
        
        <h1>Create</h1>
        
    <h4>Entry</h4>
    <hr />
    <div class="row">
    <div class="col-md-4">
    <form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Entry.Date" class="control-label"></label>
                <input asp-for="Entry.Date" class="form-control" />
                <span asp-validation-for="Entry.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Entry.PartnerId" class="control-label"></label>
                <select asp-for="Entry.PartnerId" class ="form-control" asp-items="ViewBag.PartnerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Entry.GestionId" class="control-label"></label>
                <select asp-for="Entry.GestionId" class ="form-control" asp-items="ViewBag.GestionId"></select>
            </div>            
            <div class="form-group">
                <label asp-for="DetailedEntry.ProductId" class="control-label"></label>
                <select asp-for="DetailedEntry.ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DetailedEntry.Quantity" class="control-label"></label>
                <input asp-for="DetailedEntry.Quantity" class="form-control" type="numeric">
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Entries/Delete.cshtml
@page
@model miniProiect2.Pages.Entries.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Entry</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entry.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entry.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entry.Partner)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entry.Partner.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entry.Gestion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entry.Gestion.Id)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Entry.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Entries/Details.cshtml
@page
@model miniProiect2.Pages.Entries.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Entry</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entry.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entry.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entry.Partner)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entry.Partner.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Entry.Gestion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Entry.Gestion.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Entry.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Entries/Edit.cshtml
@page
@model miniProiect2.Pages.Entries.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Entry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Entry.Id" />
            <div class="form-group">
                
                <label asp-for="Entry.Date" class="control-label"></label>
                <input asp-for="Entry.Date" class="form-control" />
                <span asp-validation-for="Entry.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="Entry.PartnerId" class="control-label"></label>
                <select asp-for="Entry.PartnerId" class="form-control" asp-items="ViewBag.PartnerId"></select>
                <span asp-validation-for="Entry.PartnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="Entry.GestionId" class="control-label"></label>
                <select asp-for="Entry.GestionId" class="form-control" asp-items="ViewBag.GestionId"></select>
                <span asp-validation-for="Entry.GestionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Entries/Index.cshtml
@page
@model miniProiect2.Pages.Entries.IndexModel

@{
    ViewData["Title"] = "Index";
}
<h1>Intrari</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Entry[0].Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Entry[0].Partner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Entry[0].Gestion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Entry) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Partner.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gestion.Name)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a> |
                <form method="post" asp-page-handler="Select">
                    <input type="hidden" name="id" value="@item.Id" />
                    <button type="submit">Select</button>
                </form>
            </td>

        </tr>
}
    </tbody>
</table>

@if (Model.detailedEntry != null)
{
    <h2>Detailed Entry</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.detailedEntry.Id</td>
                <td>@Model.detailedEntry.Product.Price</td>
                <td>@Model.detailedEntry.Quantity</td>
                <td>@Model.detailedEntry.Value</td>
            </tr>
        </tbody>
    </table>
}